# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvcache.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kvcache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkvcache.proto\x12\x07lmcache\"|\n\x11TransferKvRequest\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x10\n\x08position\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x03(\r\x12\x11\n\ttarget_ip\x18\x04 \x01(\t\x12\x13\n\x0btarget_port\x18\x05 \x01(\x05\x12\x0f\n\x07\x64o_copy\x18\x06 \x01(\x08\"$\n\x12TransferKvResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x8f\x01\n\x17RegisterInstanceRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x64p_rank\x18\x02 \x01(\r\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x11\n\tinit_port\x18\x04 \x01(\r\x12\x10\n\x08rpc_port\x18\x05 \x01(\r\x12\x12\n\nmodel_name\x18\x06 \x01(\t\x12\x0b\n\x03url\x18\x07 \x01(\t\"+\n\x18RegisterInstanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xad\x01\n\x0bLMCacheGrpc\x12\x45\n\nTransferKv\x12\x1a.lmcache.TransferKvRequest\x1a\x1b.lmcache.TransferKvResponse\x12W\n\x10RegisterInstance\x12 .lmcache.RegisterInstanceRequest\x1a!.lmcache.RegisterInstanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvcache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSFERKVREQUEST']._serialized_start=26
  _globals['_TRANSFERKVREQUEST']._serialized_end=150
  _globals['_TRANSFERKVRESPONSE']._serialized_start=152
  _globals['_TRANSFERKVRESPONSE']._serialized_end=188
  _globals['_REGISTERINSTANCEREQUEST']._serialized_start=191
  _globals['_REGISTERINSTANCEREQUEST']._serialized_end=334
  _globals['_REGISTERINSTANCERESPONSE']._serialized_start=336
  _globals['_REGISTERINSTANCERESPONSE']._serialized_end=379
  _globals['_LMCACHEGRPC']._serialized_start=382
  _globals['_LMCACHEGRPC']._serialized_end=555
# @@protoc_insertion_point(module_scope)
