syntax = "proto3";

package lmcache;

service LMCacheGrpc {
    rpc TransferKv(TransferKvRequest) returns (TransferKvResponse);
    rpc RegisterInstance(RegisterInstanceRequest) returns (RegisterInstanceResponse);
}

// 1.迁移KV Cache
message TransferKvRequest {
    bytes hash = 1;
    string position = 2; 
    repeated uint32 offset = 3;
    string target_ip = 4;
    int32 target_port = 5;
    bool do_copy = 6;
}

message TransferKvResponse {
    int32 status = 1;
}

// 2.数据服务器向元数据服务器注册推理实例信息
message RegisterInstanceRequest {
    uint64 worker_id = 1;     
    uint32 dp_rank = 2;
    string ip = 3;                      // IP地址（字符串形式）
    uint32 init_port = 4;               // nixl init端口
    uint32 rpc_port = 5;                // rpc端口
    string model_name = 6;              // 模型名称
    string url = 7;                     // 实例url 
}

message RegisterInstanceResponse {
    bool success = 1;
}