# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lmcache.v1.remote.kvcache_pb2 as kvcache__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kvcache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KvMeta2DataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadKvMeta = channel.unary_unary(
                '/kvcache.KvMeta2Data/UploadKvMeta',
                request_serializer=kvcache__pb2.UploadKvMetaRequest.SerializeToString,
                response_deserializer=kvcache__pb2.UploadKvMetaResponse.FromString,
                _registered_method=True)
        self.RegisterInstance = channel.unary_unary(
                '/kvcache.KvMeta2Data/RegisterInstance',
                request_serializer=kvcache__pb2.RegisterInstanceRequest.SerializeToString,
                response_deserializer=kvcache__pb2.RegisterInstanceResponse.FromString,
                _registered_method=True)
        self.RemoveKvMeta = channel.unary_unary(
                '/kvcache.KvMeta2Data/RemoveKvMeta',
                request_serializer=kvcache__pb2.RemoveKvMetaRequest.SerializeToString,
                response_deserializer=kvcache__pb2.RemoveKvMetaResponse.FromString,
                _registered_method=True)
        self.NewRequest = channel.unary_unary(
                '/kvcache.KvMeta2Data/NewRequest',
                request_serializer=kvcache__pb2.NewRequestRequest.SerializeToString,
                response_deserializer=kvcache__pb2.NewRequestResponse.FromString,
                _registered_method=True)
        self.RequestEnd = channel.unary_unary(
                '/kvcache.KvMeta2Data/RequestEnd',
                request_serializer=kvcache__pb2.RequestEndRequest.SerializeToString,
                response_deserializer=kvcache__pb2.RequestEndResponse.FromString,
                _registered_method=True)


class KvMeta2DataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadKvMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveKvMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KvMeta2DataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadKvMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadKvMeta,
                    request_deserializer=kvcache__pb2.UploadKvMetaRequest.FromString,
                    response_serializer=kvcache__pb2.UploadKvMetaResponse.SerializeToString,
            ),
            'RegisterInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterInstance,
                    request_deserializer=kvcache__pb2.RegisterInstanceRequest.FromString,
                    response_serializer=kvcache__pb2.RegisterInstanceResponse.SerializeToString,
            ),
            'RemoveKvMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveKvMeta,
                    request_deserializer=kvcache__pb2.RemoveKvMetaRequest.FromString,
                    response_serializer=kvcache__pb2.RemoveKvMetaResponse.SerializeToString,
            ),
            'NewRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.NewRequest,
                    request_deserializer=kvcache__pb2.NewRequestRequest.FromString,
                    response_serializer=kvcache__pb2.NewRequestResponse.SerializeToString,
            ),
            'RequestEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestEnd,
                    request_deserializer=kvcache__pb2.RequestEndRequest.FromString,
                    response_serializer=kvcache__pb2.RequestEndResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvcache.KvMeta2Data', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvcache.KvMeta2Data', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KvMeta2Data(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadKvMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KvMeta2Data/UploadKvMeta',
            kvcache__pb2.UploadKvMetaRequest.SerializeToString,
            kvcache__pb2.UploadKvMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KvMeta2Data/RegisterInstance',
            kvcache__pb2.RegisterInstanceRequest.SerializeToString,
            kvcache__pb2.RegisterInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveKvMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KvMeta2Data/RemoveKvMeta',
            kvcache__pb2.RemoveKvMetaRequest.SerializeToString,
            kvcache__pb2.RemoveKvMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KvMeta2Data/NewRequest',
            kvcache__pb2.NewRequestRequest.SerializeToString,
            kvcache__pb2.NewRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KvMeta2Data/RequestEnd',
            kvcache__pb2.RequestEndRequest.SerializeToString,
            kvcache__pb2.RequestEndResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class KvMeta2MetaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKvMeta = channel.unary_unary(
                '/kvcache.KvMeta2Meta/GetKvMeta',
                request_serializer=kvcache__pb2.GetKvMetaRequest.SerializeToString,
                response_deserializer=kvcache__pb2.GetKvMetaResponse.FromString,
                _registered_method=True)
        self.UpdateKvMeta = channel.unary_unary(
                '/kvcache.KvMeta2Meta/UpdateKvMeta',
                request_serializer=kvcache__pb2.UpdateKvMetaRequest.SerializeToString,
                response_deserializer=kvcache__pb2.UpdateKvMetaResponse.FromString,
                _registered_method=True)
        self.SearchKvBlock = channel.unary_unary(
                '/kvcache.KvMeta2Meta/SearchKvBlock',
                request_serializer=kvcache__pb2.SearchKvBlockRequest.SerializeToString,
                response_deserializer=kvcache__pb2.SearchKvBlockResponse.FromString,
                _registered_method=True)
        self.SearchKvBlockByPrompts = channel.unary_unary(
                '/kvcache.KvMeta2Meta/SearchKvBlockByPrompts',
                request_serializer=kvcache__pb2.SearchKvBlockByPromptsRequest.SerializeToString,
                response_deserializer=kvcache__pb2.SearchKvBlockByPromptsResponse.FromString,
                _registered_method=True)


class KvMeta2MetaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKvMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKvMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKvBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKvBlockByPrompts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KvMeta2MetaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKvMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKvMeta,
                    request_deserializer=kvcache__pb2.GetKvMetaRequest.FromString,
                    response_serializer=kvcache__pb2.GetKvMetaResponse.SerializeToString,
            ),
            'UpdateKvMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKvMeta,
                    request_deserializer=kvcache__pb2.UpdateKvMetaRequest.FromString,
                    response_serializer=kvcache__pb2.UpdateKvMetaResponse.SerializeToString,
            ),
            'SearchKvBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKvBlock,
                    request_deserializer=kvcache__pb2.SearchKvBlockRequest.FromString,
                    response_serializer=kvcache__pb2.SearchKvBlockResponse.SerializeToString,
            ),
            'SearchKvBlockByPrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKvBlockByPrompts,
                    request_deserializer=kvcache__pb2.SearchKvBlockByPromptsRequest.FromString,
                    response_serializer=kvcache__pb2.SearchKvBlockByPromptsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvcache.KvMeta2Meta', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvcache.KvMeta2Meta', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KvMeta2Meta(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKvMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KvMeta2Meta/GetKvMeta',
            kvcache__pb2.GetKvMetaRequest.SerializeToString,
            kvcache__pb2.GetKvMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKvMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KvMeta2Meta/UpdateKvMeta',
            kvcache__pb2.UpdateKvMetaRequest.SerializeToString,
            kvcache__pb2.UpdateKvMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKvBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KvMeta2Meta/SearchKvBlock',
            kvcache__pb2.SearchKvBlockRequest.SerializeToString,
            kvcache__pb2.SearchKvBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKvBlockByPrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.KvMeta2Meta/SearchKvBlockByPrompts',
            kvcache__pb2.SearchKvBlockByPromptsRequest.SerializeToString,
            kvcache__pb2.SearchKvBlockByPromptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
