# SPDX-License-Identifier: Apache-2.0
# Standard
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, List, Optional, Sequence, TypeAlias, Union
import asyncio
import time
import uuid
from collections import OrderedDict

# Third Party
import msgspec
import torch
import zmq

# First Party
from lmcache.logging import init_logger
from lmcache.utils import CacheEngineKey, CacheEvent
from lmcache.v1.config import LMCacheEngineConfig
from lmcache.v1.memory_management import (
    MemoryFormat,
    MemoryObj,
    PagedCpuGpuMemoryAllocator,
)
from lmcache.v1.metadata import LMCacheMetadata
from lmcache.v1.rpc_utils import get_zmq_context, get_zmq_socket
from lmcache.v1.storage_backend.abstract_backend import (
    StorageBackendInterface,
    StoragePluginInterface,
)
from lmcache.v1.storage_backend.local_cpu_backend import LocalCPUBackend
from lmcache.v1.kv_event_utils import (
    build_migrated_store_events,
    build_stored_block_metadata,
    validate_full_sequence_token_ids,
)
from lmcache.v1.token_database import (
    ChunkedTokenDatabase,
    SegmentTokenDatabase,
    TokenDatabase,
)
from lmcache.v1.transfer_channel import CreateTransferChannel
from lmcache.v1.transfer_channel.transfer_utils import (
    P2PInitSideMsg as KvTransferInitSideMsg,
    P2PInitSideRetMsg as KvTransferInitSideRetMsg,
)
from lmcache.v1.transfer_channel.nixl_channel import (
    NixlInitRequest,
    NixlInitResponse,
    NixlMemRegRequest,
    NixlMemRegResponse,
    NixlMsg,
)
from lmcache.v1.transfer_channel.transfer_utils import SideMsg

if TYPE_CHECKING:
    # First Party
    from lmcache.v1.worker import LMCacheWorker

logger = init_logger(__name__)

ChunkHash: TypeAlias = Union[int, bytes]

# Sentinel mem_index when the sender does not hold KV data for a sequence chunk.
KV_TRANSFER_MEM_INDEX_UNAVAILABLE = -1


class KvTransferMsgBase(msgspec.Struct, tag=True):
    """Base class for all KV transfer-related messages"""

    pass


class BatchedLookupAndGetMsg(KvTransferMsgBase):
    """Lookup and retrieve message"""

    # Unique event ID for request-response correlation
    event_id: str

    lookup_id: str

    receiver_id: str

    # Prefix chunk hashes generated by source
    hashes: list[ChunkHash]

    # Number of tokens for each chunk
    offsets: list[int]

    # Indexes (remote) of allocated memory objects (to be written)
    mem_indexes: list[int]


class BatchedLookupAndGetRetMsg(KvTransferMsgBase):
    """Lookup and retrieve response message"""

    # Unique event ID for request-response correlation
    event_id: str

    # Number of hit chunks
    num_hit_chunks: int


class BatchedLookupAndPutMsg(KvTransferMsgBase):
    """Batched PUT request message"""

    # Unique event ID for request-response correlation
    event_id: str

    sender_id: str

    # Prefix chunk hashes generated by source
    hashes: list[ChunkHash]

    # Number of tokens for each chunk
    offsets: list[int]

    # Indexes (remote) of allocated memory objects (to be read)
    mem_indexes: list[int]

    # Optional flat token ids for the full transfer request
    token_ids: list[int] | None = None

    # Optional parent hash for each transferred chunk
    parent_hashes: list[ChunkHash | None] | None = None


class BatchedLookupAndPutRetMsg(KvTransferMsgBase):
    """Batched PUT response message"""

    # Unique event ID for request-response correlation
    event_id: str

    # Number of chunks newly read from the sender
    num_read_chunks: int

    # Number of requested chunks already present on the receiver
    num_existing_chunks: int = 0


@dataclass(frozen=True)
class KvTransferPeerResult:
    num_read_chunks: int
    num_existing_chunks: int
    num_requested_chunks: int
    failed: bool = False

    @property
    def num_satisfied_chunks(self) -> int:
        return self.num_read_chunks + self.num_existing_chunks

    @property
    def all_already_satisfied(self) -> bool:
        return (
            self.num_requested_chunks > 0
            and self.num_existing_chunks == self.num_requested_chunks
            and self.num_read_chunks == 0
            and not self.failed
        )


KvTransferMsg = Union[
    BatchedLookupAndGetMsg,
    BatchedLookupAndGetRetMsg,
    BatchedLookupAndPutMsg,
    BatchedLookupAndPutRetMsg,
]


class KvTransferBackend(StoragePluginInterface):
    """
    KV Transfer Storage Backend for node-to-node KV cache transfer with connection reuse.
    
    Features:
    - Arbitrary node-to-node KV transfer via ZMQ ports
    - Connection pooling with LRU eviction and idle timeout
    - Bidirectional transfer (GET/PUT operations)
    """
    def __init__(
        self,
        dst_device: str = "cuda",
        config: LMCacheEngineConfig | None = None,
        metadata: LMCacheMetadata | None = None,
        local_cpu_backend: LocalCPUBackend | None = None,
        loop: asyncio.AbstractEventLoop | None = None,
        max_connections: int | None = None,
        idle_timeout_seconds: float | None = None,
        cleanup_interval_seconds: float | None = None,
    ):
        assert config is not None
        assert metadata is not None
        assert local_cpu_backend is not None
        assert loop is not None
        super().__init__(
            dst_device=dst_device,
            config=config,
            metadata=metadata,
            local_cpu_backend=local_cpu_backend,
            loop=loop,
        )
        self.loop = loop
        assert config.kv_transfer_host is not None, (
            "kv_transfer_host must be specified"
        )
        assert config.kv_transfer_init_port is not None, (
            "kv_transfer_init_port must be specified"
        )

        # Current node's worker id
        self.worker_id = metadata.worker_id

        # Current node's connection information
        self.local_host = config.kv_transfer_host
        self.local_init_port = config.kv_transfer_init_port
        self.local_init_url = f"{self.local_host}:{self.local_init_port}"

        # ===== Connection Pool Configuration =====
        max_connections = (
            max_connections
            if max_connections is not None
            else config.kv_transfer_max_connections
        )
        idle_timeout_seconds = (
            idle_timeout_seconds
            if idle_timeout_seconds is not None
            else config.kv_transfer_idle_timeout_seconds
        )
        cleanup_interval_seconds = (
            cleanup_interval_seconds
            if cleanup_interval_seconds is not None
            else config.kv_transfer_cleanup_interval_seconds
        )
        # Maximum number of concurrent peer connections
        self.max_connections = max_connections
        # Idle timeout in seconds - connections unused for this duration will be closed
        self.idle_timeout_seconds = idle_timeout_seconds
        # Interval for running cleanup task
        self.cleanup_interval_seconds = cleanup_interval_seconds
        
        logger.info(
            f"KvTransfer Backend connection pool configured: "
            f"max_connections={max_connections}, "
            f"idle_timeout={idle_timeout_seconds}s, "
            f"cleanup_interval={cleanup_interval_seconds}s"
        )

        # ===== Connection Management for Arbitrary KV Transfers =====
        # These data structures enable connection reuse for efficient KV transfers
        
        # Set of connected peer_init_urls
        # Using OrderedDict to maintain insertion order for LRU eviction
        self.connected_peers: OrderedDict[str, bool] = OrderedDict()
        
        # Tracks last access time for each peer connection (for idle timeout)
        # Maps peer_init_url -> last_used_timestamp
        self.peer_last_used_time: dict[str, float] = {}
        
        # Temporary mapping for ongoing lookup operations
        # Maps lookup_id -> (peer_init_url, location)
        # This allows batched_get to find the correct peer after batched_contains
        self.lookup_id_to_peer_mapping: dict[str, tuple[str, str]] = {}

        # TODO(Jiayi): support gpu and local storage kv transfer as well.
        self.local_cpu_backend = local_cpu_backend
        self.memory_allocator = local_cpu_backend.get_memory_allocator()
        assert isinstance(
            self.memory_allocator, PagedCpuGpuMemoryAllocator
        ), (
            "KvTransferBackend requires PagedCpuGpuMemoryAllocator. "
            "Set enable_kv_transfer=True so LocalCPUBackend initializes "
            "a paged allocator, or verify allocator initialization."
        )

        self.dtype = metadata.kv_dtype
        self.token_database: TokenDatabase
        if config.enable_blending:
            self.token_database = SegmentTokenDatabase(config, metadata)
        else:
            self.token_database = ChunkedTokenDatabase(config, metadata)

        cpu_allocator = self.memory_allocator.cpu_allocator
        if hasattr(cpu_allocator, "shape"):
            self.full_size_shape = list(cpu_allocator.shape)
        elif hasattr(cpu_allocator, "shapes"):
            # PagedTensorMemoryAllocator exposes `shapes` (list[torch.Size]).
            self.full_size_shape = list(cpu_allocator.shapes[0])
        else:
            self.full_size_shape = list(metadata.get_shapes()[0])
        self.fmt: MemoryFormat = (
            MemoryFormat.KV_MLA_FMT if metadata.use_mla else MemoryFormat.KV_2LTD
        )
        self.chunk_size = config.chunk_size

        # Transfer channel for KV transfer communication
        # (supports both sender and receiver roles)
        # NOTE: peer_init_url is set to None to disable the built-in init loop
        # We handle init requests in _handle_init_requests() instead
        self.transfer_channel = CreateTransferChannel(
            channel_type=config.transfer_channel,
            async_mode=True,
            role="both",
            buffer_ptr=self.memory_allocator.cpu_allocator.buffer_ptr,
            buffer_size=self.memory_allocator.cpu_allocator.buffer_size,
            align_bytes=self.memory_allocator.cpu_allocator.align_bytes,
            tp_rank=self.worker_id,
            peer_init_url=None,  # Disable built-in init loop
            backends=config.nixl_backends,
            event_loop=loop,
        )

        # KV events — this list is owned by CacheEngine and injected via
        # set_kv_events_sink(); events are appended directly to the engine's
        # list so that consumers only need to poll one place.
        self.kv_events: Optional[List[CacheEvent]] = None

        # ===== ZMQ Socket Management for Connection Reuse =====
        # Uses ROUTER/DEALER pattern for concurrent multi-client requests
        
        self.running = True
        
        # Maps peer_init_url -> ZMQ DEALER socket for sending requests to peer
        # DEALER sockets support concurrent requests without blocking
        self.peer_to_socket_mapping: dict[str, zmq.Socket] = {}
        
        # ===== Lock-free Request-Response Correlation =====
        # Maps event_id -> asyncio.Future for pending requests
        # Allows concurrent requests without locks
        self.pending_requests: dict[str, asyncio.Future] = {}
        # Lock only for modifying pending_requests dict (very fast)
        self._pending_requests_lock = asyncio.Lock()
        
        # Lock to protect concurrent peer connection establishment
        # Maps peer_init_url -> asyncio.Lock to prevent duplicate connections
        self._peer_connection_locks: dict[str, asyncio.Lock] = {}
        # Global lock for accessing _peer_connection_locks dict
        self._peer_connection_locks_lock = asyncio.Lock()
        
        # Connection pool statistics
        self.connection_pool_stats = {
            "total_connections_created": 0,
            "total_connections_closed": 0,
            "lru_evictions": 0,
            "idle_timeouts": 0,
        }
        
        # Start background tasks
        asyncio.run_coroutine_threadsafe(self._handle_init_requests(), loop)
        asyncio.run_coroutine_threadsafe(self._connection_cleanup_task(), loop)

    def __str__(self) -> str:
        return "KvTransferBackend"

    async def batched_async_contains(
        self,
        lookup_id: str,
        keys: List[CacheEngineKey],
        pin: bool = False,
    ) -> int:
        # KvTransferBackend does not support lookup without explicit peer connection
        return NotImplementedError

    async def _handle_init_requests(self):
        """Handle initialization requests and KV transfer requests from peer nodes.
        
        Uses ROUTER socket to support concurrent multi-client requests.
        ROUTER sockets automatically track client identity for routing responses.
        """
        logger.info(f"Starting KvTransfer ROUTER handler at {self.local_init_url}")
        self.async_context = get_zmq_context()
        self.init_socket = get_zmq_socket(
            self.async_context,
            self.local_init_url,
            "tcp",
            zmq.ROUTER,
            "bind",
        )

        while self.running:
            try:
                # ROUTER socket receives: [identity, empty_frame, message]
                frames = await self.init_socket.recv_multipart()
                if len(frames) < 2:
                    logger.warning(f"Received malformed message with {len(frames)} frames")
                    continue
                
                # Extract identity and message
                identity = frames[0]
                # Handle both [identity, message] and [identity, empty, message] formats
                req_bytes = frames[-1]

                # Try to decode as NixlMsg or SideMsg first (init messages)
                try:
                    req = msgspec.msgpack.decode(
                        req_bytes, type=Union[NixlMsg, SideMsg]
                    )
                    resp = await self._handle_init_msg(req)
                except Exception:
                    # If not init message, try KvTransferMsg (lookup requests)
                    req = msgspec.msgpack.decode(req_bytes, type=KvTransferMsg)
                    resp = await self._handle_kv_transfer_msg(req)

                # ROUTER socket sends: [identity, empty_frame, message]
                await self.init_socket.send_multipart([
                    identity,
                    b"",
                    msgspec.msgpack.encode(resp)
                ])

            except Exception as e:
                logger.error(f"Failed to process request: {e}")
                if self.running:
                    await asyncio.sleep(0.01)

    async def _handle_init_msg(
        self, req: Union[NixlMsg, KvTransferInitSideMsg]
    ) -> Union[NixlMsg, KvTransferInitSideRetMsg]:
        """Handle two-phase initialization: metadata exchange, memory registration."""
        if isinstance(req, NixlInitRequest):
            # Phase 1: Exchange agent metadata
            agent_name = self.transfer_channel.nixl_agent.add_remote_agent(
                req.local_meta_bytes
            )
            resp = NixlInitResponse(
                remote_agent_name=agent_name,
                remote_meta_bytes=self.transfer_channel.nixl_agent.get_agent_metadata(),
            )
            logger.debug("Phase 1: metadata exchange completed")
            return resp

        elif isinstance(req, NixlMemRegRequest):
            # Phase 2: Register memory descriptors
            local_xfer_descs = self.transfer_channel.nixl_agent.get_serialized_descs(
                self.transfer_channel.nixl_wrapper.xfer_descs
            )

            remote_xfer_dlist_bytes = req.local_xfer_dlist_bytes
            remote_xfer_dlist = self.transfer_channel.nixl_agent.deserialize_descs(
                remote_xfer_dlist_bytes
            )
            remote_xfer_handlers = self.transfer_channel.nixl_agent.prep_xfer_dlist(
                req.remote_agent_name, remote_xfer_dlist
            )
            
            # Store remote xfer handlers using the remote peer's local_id
            peer_init_url = req.local_id
            self.transfer_channel.remote_xfer_handlers_dict[peer_init_url] = (
                remote_xfer_handlers
            )
            
            logger.debug(f"Phase 2: memory registration completed for peer {peer_init_url}")
            return NixlMemRegResponse(remote_xfer_dlist_bytes=local_xfer_descs)

        elif isinstance(req, KvTransferInitSideMsg):
            # Phase 3: No longer needed, just acknowledge
            logger.debug("Phase 3: handshake completed")
            return KvTransferInitSideRetMsg(peer_lookup_url="")

        else:
            raise ValueError(f"Unsupported InitMsg type: {type(req)}")

    async def _handle_kv_transfer_msg(
        self,
        msg: KvTransferMsg,
    ) -> KvTransferMsg:
        """Handle KV transfer requests (GET/PUT) from peer nodes."""
        if isinstance(msg, BatchedLookupAndGetMsg):
            # Handle GET request from a peer node
            event_id = msg.event_id
            logger.info(
                f"Received KV transfer batched GET request from receiver "
                f"{msg.receiver_id} (event_id={event_id})"
            )

            lookup_id = msg.lookup_id
            receiver_id = msg.receiver_id
            remote_mem_indexes = msg.mem_indexes
            hashes = msg.hashes
            offsets = msg.offsets
            keys = self._build_local_keys_from_hashes_offsets(hashes, offsets)
            logger.info(
                "GET request rebuilt %d keys from %d hashes",
                len(keys),
                len(hashes),
            )
            
            # Validate input lists have consistent lengths
            if not (len(keys) == len(remote_mem_indexes) == len(offsets)):
                error_msg = (
                    f"Inconsistent list lengths in BatchedLookupAndGetMsg: "
                    f"hashes={len(hashes)}, offsets={len(offsets)}, "
                    f"mem_indexes={len(remote_mem_indexes)}"
                )
                logger.error(error_msg)
                raise ValueError(error_msg)

            # Look up keys in local storage
            num_hit_chunks = await self.local_cpu_backend.batched_async_contains(
                lookup_id=lookup_id,
                keys=keys,
                pin=True,
            )

            if num_hit_chunks == 0:
                return BatchedLookupAndGetRetMsg(
                    event_id=event_id,
                    num_hit_chunks=0,
                )

            # Retrieve the KV cache data from local storage
            mem_objs = await self.local_cpu_backend.batched_get_non_blocking(
                lookup_id=lookup_id,
                keys=keys[:num_hit_chunks],
            )

            # Transfer data to the requesting peer node
            channel_transfer_spec = {
                "receiver_id": receiver_id,
                "remote_indexes": remote_mem_indexes[:num_hit_chunks],
            }
            await self.transfer_channel.async_batched_write(
                objects=mem_objs,
                transfer_spec=channel_transfer_spec,
            )

            ret_msg = BatchedLookupAndGetRetMsg(
                event_id=event_id,
                num_hit_chunks=num_hit_chunks,
            )

            # Clean up memory references
            for mem_obj in mem_objs:
                mem_obj.ref_count_down()
                mem_obj.unpin()

            return ret_msg

        elif isinstance(msg, BatchedLookupAndPutMsg):
            # Handle PUT request from a peer node
            event_id = msg.event_id
            logger.info(
                f"Received KV transfer batched PUT request from sender "
                f"{msg.sender_id} (event_id={event_id})"
            )

            sender_id = msg.sender_id
            r_mem_indexes = msg.mem_indexes
            hashes = msg.hashes
            offsets = msg.offsets
            token_ids = msg.token_ids
            keys = self._build_local_keys_from_hashes_offsets(hashes, offsets)
            logger.info(
                "PUT request rebuilt %d keys from %d hashes",
                len(keys),
                len(hashes),
            )
            
            # Validate input lists have consistent lengths
            if not (len(keys) == len(r_mem_indexes) == len(offsets)):
                error_msg = (
                    f"Inconsistent list lengths in BatchedLookupAndPutMsg: "
                    f"hashes={len(hashes)}, mem_indexes={len(r_mem_indexes)}, "
                    f"offsets={len(offsets)}"
                )
                logger.error(error_msg)
                raise ValueError(error_msg)

            # Filter out keys that already exist locally
            r_mem_indexes_to_read = []
            keys_to_read = []
            pre_existing_keys: list[CacheEngineKey] = []
            offsets_to_read = []
            local_mem_objs = []
            existing_chunks_count = 0
            try:
                for idx, key in enumerate(keys):
                    if r_mem_indexes[idx] == KV_TRANSFER_MEM_INDEX_UNAVAILABLE:
                        logger.info(
                            "Key %s has no source data (mem_index unavailable); "
                            "stopping transfer of remaining chunks because "
                            "suffix blocks without prefix are unusable",
                            key,
                        )
                        self._remove_stale_suffix_keys(keys[idx:])
                        break

                    if self.local_cpu_backend.contains(key, pin=False):
                        pre_existing_keys.append(key)
                        existing_chunks_count += 1
                        logger.debug(f"Key {key} already exists locally, skipping")
                        continue

                    # Allocate memory for incoming data
                    shape = self.full_size_shape.copy()
                    shape[self.fmt.token_dim()] = offsets[idx]
                    local_mem_obj = self.local_cpu_backend.allocate(
                        torch.Size(shape),
                        self.dtype,
                        self.fmt,
                        busy_loop=False,
                    )
                    if local_mem_obj is None:
                        logger.warning(
                            "KV transfer put allocation failed for key %s, "
                            "skipping remaining chunks in this batch",
                            key,
                        )
                        break

                    r_mem_indexes_to_read.append(r_mem_indexes[idx])
                    local_mem_objs.append(local_mem_obj)
                    keys_to_read.append(key)
                    offsets_to_read.append(offsets[idx])

                # Receive data from the sending peer node
                if keys_to_read:
                    channel_transfer_spec = {
                        "sender_id": sender_id,
                        "remote_indexes": r_mem_indexes_to_read,
                    }
                    await self.transfer_channel.async_batched_read(
                        buffers=local_mem_objs,
                        transfer_spec=channel_transfer_spec,
                    )

                # Store received data in local backend
                self.local_cpu_backend.batched_submit_put_task(
                    keys=keys_to_read,
                    memory_objs=local_mem_objs,
                )

                logger.info(
                    "KV transfer PUT satisfied %d/%d chunks "
                    "(%d newly read, %d already existed; event_id=%s)",
                    len(local_mem_objs) + existing_chunks_count,
                    len(keys),
                    len(local_mem_objs),
                    existing_chunks_count,
                    event_id,
                )

                # Publish KV store events only for newly migrated chunks.
                self._publish_migrated_kv_store_events(
                    migrated_keys=keys_to_read,
                    pre_existing_keys=pre_existing_keys,
                    token_ids=token_ids,
                    offsets=offsets,
                    event_id=event_id,
                    report_metadata=True,
                )

                return BatchedLookupAndPutRetMsg(
                    event_id=event_id,
                    num_read_chunks=len(local_mem_objs),
                    num_existing_chunks=existing_chunks_count,
                )
            finally:
                for mem_obj in local_mem_objs:
                    mem_obj.ref_count_down()

        else:
            raise ValueError(f"Unsupported KvTransferMsg type: {type(msg)}")

    def _build_local_keys_from_hashes_offsets(
        self,
        hashes: list[ChunkHash],
        offsets: list[int],
    ) -> list[CacheEngineKey]:
        """Build local cache keys from chunk hashes and offsets."""
        keys: list[CacheEngineKey] = []
        for _, _, key in self.token_database.process_tokens(
            hashes=hashes,
            offsets=offsets,
        ):
            assert isinstance(key, CacheEngineKey)
            keys.append(key)
        logger.debug(
            "Rebuilt %d local keys from %d hashes in KvTransferBackend",
            len(keys),
            len(hashes),
        )
        return keys

    def _remove_stale_suffix_keys(self, keys: Sequence[CacheEngineKey]) -> int:
        """Remove suffix chunks that remain locally after a source prefix gap."""
        keys_to_remove = [
            key
            for key in keys
            if self.local_cpu_backend.contains(key, pin=False)
        ]
        if not keys_to_remove:
            return 0

        removed = self.local_cpu_backend.batched_remove(keys_to_remove)
        logger.info(
            "Removed %d stale suffix KV chunks after source prefix gap",
            removed,
        )
        return removed

    def _publish_migrated_kv_store_events(
        self,
        migrated_keys: list[CacheEngineKey],
        pre_existing_keys: list[CacheEngineKey],
        token_ids: Optional[list[int]],
        offsets: list[int],
        event_id: str,
        report_metadata: bool = False,
    ) -> None:
        """Publish store events only for newly migrated chunks."""
        if not migrated_keys or not token_ids:
            return

        if not validate_full_sequence_token_ids(token_ids, offsets, event_id):
            return

        pre_existing_hashes = {key.chunk_hash for key in pre_existing_keys}
        if report_metadata and self.local_cpu_backend.metadata_reporter is not None:
            descriptors = build_stored_block_metadata(
                self.token_database,
                token_ids,
                migrated_keys,
            )
            self.local_cpu_backend.metadata_reporter.on_kv_stored_structured(
                descriptors
            )
        if self.kv_events is None:
            return
        for event in build_migrated_store_events(
            self.token_database,
            token_ids,
            migrated_keys,
            pre_existing_hashes,
        ):
            logger.debug(
                "Added kv cache event '%s' to kv cache events queue",
                event,
            )
            self.kv_events.append(event)

    async def _ensure_peer_connection(
        self,
        peer_init_url: str,
    ) -> None:
        """
        Establish connection to an arbitrary peer node if not connected.
        
        Args:
            peer_init_url: The initialization URL (ZMQ port) of the peer
                          Format: "host:port" (e.g., "192.168.1.100:5555")
        """
        # Fast path: Check if connection already exists (connection reuse)
        # This check is outside the lock for better performance
        if peer_init_url in self.connected_peers:
            # Update last used time
            self.peer_last_used_time[peer_init_url] = time.time()
            # Move to end for LRU tracking (most recently used)
            self.connected_peers.move_to_end(peer_init_url)
            # logger.info(
            #     f"Reusing existing connection to peer {peer_init_url} "
            # )
            return
        
        # Get or create a lock for this specific peer to prevent concurrent
        # connection attempts to the same peer
        async with self._peer_connection_locks_lock:
            if peer_init_url not in self._peer_connection_locks:
                self._peer_connection_locks[peer_init_url] = asyncio.Lock()
            peer_lock = self._peer_connection_locks[peer_init_url]
        
        # Acquire the peer-specific lock to ensure only one coroutine
        # establishes the connection
        async with peer_lock:
            # Double-check after acquiring the lock (another coroutine may have
            # established the connection while we were waiting for the lock)
            if peer_init_url in self.connected_peers:
                # Update last used time
                self.peer_last_used_time[peer_init_url] = time.time()
                # Move to end for LRU tracking (most recently used)
                self.connected_peers.move_to_end(peer_init_url)
                logger.info(
                    f"Reusing existing connection to peer {peer_init_url} "
                    "(established by another coroutine)"
                )
                return
            
            # Check if nixl connection already exists in transfer channel
            # This can happen if the ZMQ socket was closed but nixl connection remains
            if peer_init_url in self.transfer_channel.remote_xfer_handlers_dict:
                logger.warning(
                    f"Nixl connection to peer {peer_init_url} already exists in "
                    "transfer channel but not in local mapping. This indicates "
                    "a state inconsistency. Skipping nixl re-initialization."
                )
                del self.transfer_channel.remote_xfer_handlers_dict[peer_init_url]
                logger.info(
                    f"Removed stale nixl connection for {peer_init_url}, "
                    "proceeding with full re-initialization"
                )
            
            # Check connection pool limit before creating new connection
            if len(self.connected_peers) >= self.max_connections:
                await self._evict_lru_connection()
                logger.info(
                    "Connection pool full (%d), evicted LRU connection "
                    "before connecting to %s",
                    self.max_connections,
                    peer_init_url,
                )
            
            logger.debug(
                "Establishing new nixl connection to peer node "
                f"at ZMQ port {peer_init_url}"
            )
                
            # Initialize nixl connection with the peer node
            # This establishes the RDMA/TCP data transfer channel
            init_side_msg = KvTransferInitSideMsg()
            await self.transfer_channel.async_lazy_init_peer_connection(
                local_id=self.local_init_url,
                peer_id=peer_init_url,
                peer_init_url=peer_init_url,
                init_side_msg=init_side_msg,
            )
            
            # Mark peer as connected
            self.connected_peers[peer_init_url] = True
            
            # Initialize last used time
            self.peer_last_used_time[peer_init_url] = time.time()

            # Create ZMQ DEALER socket for control plane communication with this peer
            # DEALER allows concurrent requests without blocking
            lookup_socket = get_zmq_socket(
                self.async_context,
                peer_init_url,
                "tcp",
                zmq.DEALER,
                "connect",
            )
            self.peer_to_socket_mapping[peer_init_url] = lookup_socket
            
            # Start background task to receive responses for this peer
            asyncio.create_task(
                self._receive_responses_from_peer(peer_init_url, lookup_socket)
            )
            
            # Update statistics
            self.connection_pool_stats["total_connections_created"] += 1
            
            logger.debug(
                "Successfully established reusable connection to peer %s (pool size: %d/%d)",
                peer_init_url,
                len(self.connected_peers),
                self.max_connections,
            )

    async def _receive_responses_from_peer(
        self,
        peer_init_url: str,
        socket: zmq.Socket,
    ) -> None:
        """
        Background task to receive responses from a peer and dispatch to pending requests.
        
        This enables lock-free concurrent requests by matching responses to requests
        via event_id.
        
        Args:
            peer_init_url: The peer's init URL (for logging)
            socket: The DEALER socket connected to the peer
        """
        logger.info(f"Starting response receiver for peer {peer_init_url}")
        
        while self.running and peer_init_url in self.connected_peers:
            try:
                # DEALER receives: [empty_frame, message]
                frames = await socket.recv_multipart()
                if len(frames) < 1:
                    logger.warning(f"Received empty response from peer {peer_init_url}")
                    continue
                
                resp_bytes = frames[-1]
                resp = msgspec.msgpack.decode(resp_bytes, type=KvTransferMsg)
                
                # Extract event_id from response
                event_id = resp.event_id
                
                # Find and complete the pending request
                async with self._pending_requests_lock:
                    if event_id in self.pending_requests:
                        future = self.pending_requests.pop(event_id)
                        future.set_result(resp)
                        logger.debug(f"Dispatched response for event_id={event_id}")
                    else:
                        logger.warning(
                            f"Received response for unknown event_id={event_id} "
                            f"from peer {peer_init_url}"
                        )
                        
            except asyncio.CancelledError:
                logger.info(f"Response receiver for peer {peer_init_url} cancelled")
                break
            except Exception as e:
                if self.running and peer_init_url in self.connected_peers:
                    logger.error(
                        f"Error receiving response from peer {peer_init_url}: {e}"
                    )
                    await asyncio.sleep(0.01)
                else:
                    break
        
        logger.info(f"Response receiver for peer {peer_init_url} stopped")

    async def _send_request_and_wait(
        self,
        peer_init_url: str,
        event_id: str,
        msg: KvTransferMsg,
    ) -> KvTransferMsg:
        """
        Send a request to a peer and wait for the response (lock-free).
        
        Args:
            peer_init_url: The peer's init URL
            event_id: Unique identifier for this request
            msg: The message to send
            
        Returns:
            The response message
        """
        # Create a future for this request
        future: asyncio.Future = asyncio.get_event_loop().create_future()
        
        async with self._pending_requests_lock:
            self.pending_requests[event_id] = future
        
        try:
            # Get the socket for this peer
            socket = self.peer_to_socket_mapping[peer_init_url]
            
            # Send the request via DEALER socket
            await socket.send_multipart([
                b"",
                msgspec.msgpack.encode(msg)
            ])
            
            # Wait for the response (handled by _receive_responses_from_peer)
            return await future
            
        except Exception as e:
            # Clean up on error
            async with self._pending_requests_lock:
                self.pending_requests.pop(event_id, None)
            raise e

    async def _evict_lru_connection(self) -> bool:
        """
        Evict the least recently used (LRU) connection from the pool.
        
        This method is called when the connection pool reaches its maximum size
        and a new connection needs to be established. It removes the connection
        that was used least recently.
        
        Returns:
            True if a connection was evicted, False if pool was empty
        """
        if not self.connected_peers:
            logger.warning("Cannot evict from empty connection pool")
            return False
        
        # Get the least recently used peer (first item in OrderedDict)
        lru_peer_init_url = next(iter(self.connected_peers))
        
        last_used = self.peer_last_used_time.get(lru_peer_init_url, 0)
        logger.info(
            "Evicting LRU connection to peer %s (last used: %.1fs ago)",
            lru_peer_init_url,
            time.time() - last_used,
        )
        
        # Close the connection
        self._close_peer_connection_internal(lru_peer_init_url)
        
        # Update statistics
        self.connection_pool_stats["lru_evictions"] += 1
        
        return True
    
    async def _connection_cleanup_task(self) -> None:
        """
        Background task that periodically cleans up idle connections.
        
        This task runs at regular intervals (cleanup_interval_seconds) and
        closes connections that have been idle for longer than idle_timeout_seconds.
        """
        logger.debug(
            f"Starting connection cleanup task "
            f"(interval: {self.cleanup_interval_seconds}s, "
            f"idle_timeout: {self.idle_timeout_seconds}s)"
        )
        
        while self.running:
            try:
                await asyncio.sleep(self.cleanup_interval_seconds)
                
                if not self.running:
                    break
                
                current_time = time.time()
                idle_peers = []
                
                # Find all idle connections
                for peer_init_url, last_used_time in self.peer_last_used_time.items():
                    idle_duration = current_time - last_used_time
                    if idle_duration > self.idle_timeout_seconds:
                        idle_peers.append((peer_init_url, idle_duration))
                
                # Close idle connections
                if idle_peers:
                    logger.info(
                        "Cleaning up %d idle connections (idle > %ds)",
                        len(idle_peers),
                        self.idle_timeout_seconds,
                    )
                    
                    for peer_init_url, idle_duration in idle_peers:
                        logger.debug(
                            f"Closing idle connection to {peer_init_url} "
                            f"(idle for {idle_duration:.1f}s)"
                        )
                        self._close_peer_connection_internal(peer_init_url)
                        self.connection_pool_stats["idle_timeouts"] += 1
                    
                    logger.info(
                        "Connection pool after cleanup: %d/%d (stats: %s)",
                        len(self.connected_peers),
                        self.max_connections,
                        self.connection_pool_stats,
                    )
                
            except Exception as e:
                logger.error(f"Error in connection cleanup task: {e}", exc_info=True)
        
        logger.info("Connection cleanup task stopped")

    async def connect_to_peer(
        self,
        peer_ip: str,
        peer_init_port: int,
    ) -> bool:
        """
        Establish connection to a peer node by IP and ports.
        
        The connection will be cached and reused for all subsequent transfers.
        
        Args:
            peer_ip: IP address of the target peer (e.g., "192.168.1.100")
            peer_init_port: Initialization port of the target peer (e.g., 5555)
        
        Returns:
            True if connection was established or already exists, False on failure
        """
        # Construct URLs from IP and ports
        peer_init_url = f"{peer_ip}:{peer_init_port}"
        
        return await self.connect_to_peer_by_zmq_port(
            peer_init_url=peer_init_url,
        )

    async def connect_to_peer_by_zmq_port(
        self,
        peer_init_url: str,
    ) -> bool:
        try:
            await self._ensure_peer_connection(peer_init_url)
            logger.info(f"Successfully connected to peer at {peer_init_url}")
            return True
        except Exception as e:
            logger.error(f"Failed to connect to peer at {peer_init_url}: {e}")
            return False

    async def batched_get_non_blocking(
        self,
        lookup_id: str,
        keys: list[CacheEngineKey],
        transfer_spec: Any = None,
        event_id: str = "",
    ) -> list[MemoryObj]:
        """
        Retrieve KV cache data from an arbitrary peer node.
        Supports fetching data from any node in the cluster with connection reuse.
        
        Args:
            lookup_id: Unique identifier for this lookup operation
            keys: List of cache keys to retrieve
            transfer_spec: Transfer specification containing chunk lengths and
                optional flat token ids for event reporting
            event_id: Optional event ID for request correlation (auto-generated if empty)
            
        Returns:
            List of memory objects containing the retrieved KV cache data
        """
        # Get peer information from the lookup mapping
        peer_init_url, location = self.lookup_id_to_peer_mapping.pop(lookup_id)
        logger.info(
            f"Retrieving {len(keys)} keys from peer node {peer_init_url} "
            f"(location: {location}, connection reused)"
        )
        
        # Update last used time and move to end (most recently used)
        self.peer_last_used_time[peer_init_url] = time.time()
        if peer_init_url in self.connected_peers:
            self.connected_peers.move_to_end(peer_init_url)

        assert isinstance(transfer_spec, dict)
        cum_chunk_lengths = transfer_spec.get("cum_chunk_lengths", None)
        token_ids = transfer_spec.get("token_ids")
        parent_hashes = transfer_spec.get("parent_hashes")
        assert cum_chunk_lengths is not None, "cum_chunk_lengths must be provided"

        # Allocate memory for incoming data
        mem_objs = []
        offsets = []
        hashes = []
        for idx, key in enumerate(keys):
            chunk_tokens = cum_chunk_lengths[idx + 1] - cum_chunk_lengths[idx]
            shape = self.full_size_shape.copy()
            shape[self.fmt.token_dim()] = chunk_tokens
            mem_obj = self.local_cpu_backend.allocate(
                torch.Size(shape),
                self.dtype,
                self.fmt,
                busy_loop=False,
            )
            if mem_obj is None:
                logger.warning(
                    "KV transfer get allocation failed after %d/%d chunks; "
                    "returning empty result to avoid blocking",
                    idx,
                    len(keys),
                )
                for allocated_mem_obj in mem_objs:
                    allocated_mem_obj.ref_count_down()
                return []
            mem_objs.append(mem_obj)
            offsets.append(chunk_tokens)
            hashes.append(key.chunk_hash)

        local_indexes = self.transfer_channel.get_local_mem_indices(mem_objs)

        # Generate event_id if not provided
        if not event_id:
            event_id = f"get_{uuid.uuid4().hex[:8]}"

        # Send GET request to the peer node via ZMQ (control plane)
        msg = BatchedLookupAndGetMsg(
            event_id=event_id,
            lookup_id=lookup_id,
            receiver_id=self.local_init_url,
            hashes=hashes,
            offsets=offsets,
            mem_indexes=local_indexes,
        )

        # Lock-free concurrent request using event_id for correlation
        try:
            ret_msg = await self._send_request_and_wait(peer_init_url, event_id, msg)
            num_hit_chunks = ret_msg.num_hit_chunks
        except Exception as e:
            logger.error(
                f"Failed to retrieve data from peer {peer_init_url}: {e}. "
                f"Returning empty result."
            )
            # Clean up allocated memory on failure
            for mem_obj in mem_objs:
                mem_obj.ref_count_down()
            return []

        logger.info(
            f"Successfully retrieved {num_hit_chunks}/{len(keys)} chunks "
            f"from peer {peer_init_url} (event_id={event_id})"
        )

        # Return hit memory objects and clean up missed ones
        hit_mem_objs = mem_objs[:num_hit_chunks]
        for missed_mem_obj in mem_objs[num_hit_chunks:]:
            missed_mem_obj.ref_count_down()

        # Publish KV store events only for prefix-hit chunks retrieved.
        if token_ids is not None and cum_chunk_lengths is not None:
            full_offsets = [
                cum_chunk_lengths[i + 1] - cum_chunk_lengths[i]
                for i in range(len(cum_chunk_lengths) - 1)
            ]
            self._publish_migrated_kv_store_events(
                migrated_keys=keys[:num_hit_chunks],
                pre_existing_keys=[],
                token_ids=token_ids,
                offsets=full_offsets,
                event_id=event_id,
            )

        return hit_mem_objs

    async def transfer_to_peer(
        self,
        peer_ip: str,
        peer_init_port: int,
        hashes: Sequence[ChunkHash],
        objs: List[MemoryObj],
        offsets: Optional[List[int]] = None,
        event_id: str = "",
        token_ids: Optional[List[int]] = None,
        parent_hashes: Optional[List[ChunkHash | None]] = None,
        mem_indexes: Optional[List[int]] = None,
    ) -> KvTransferPeerResult:
        """
        Transfer KV cache data to a specific peer node.
        
        The connection will be established automatically if not already connected,
        and will be reused for subsequent transfers.
        
        Args:
            peer_ip: IP address of the target peer (e.g., "192.168.1.100")
            peer_init_port: Initialization port of the target peer (e.g., 5555)
            hashes: List of chunk hashes to transfer
            objs: List of memory objects containing the KV cache data
            offsets: Optional token counts. If None, uses chunk_size.
            event_id: Optional event ID for request correlation (auto-generated if empty)
            token_ids: Optional flat token ids for the full sequence.
            parent_hashes: Deprecated; parent hashes are derived from token_ids.
            mem_indexes: Per-chunk source mem indexes aligned with hashes; use
                KV_TRANSFER_MEM_INDEX_UNAVAILABLE when source has no data.
        
        Returns:
            Transfer result with newly read, already existing, and requested counts
        """
        peer_init_url = f"{peer_ip}:{peer_init_port}"
        
        if offsets is None:
            offsets = [self.chunk_size] * len(hashes)
        
        transfer_spec = {
            "peer_init_url": peer_init_url,
            "offsets": offsets,
            "event_id": event_id,
            "token_ids": token_ids,
            "parent_hashes": parent_hashes,
            "mem_indexes": mem_indexes,
        }
        
        return await self.async_batched_submit_put_task(
            hashes=hashes,
            objs=objs,
            transfer_spec=transfer_spec,
        )

    async def async_batched_submit_put_task(
        self,
        hashes: Sequence[ChunkHash],
        objs: List[MemoryObj],
        transfer_spec: Any = None,
    ) -> KvTransferPeerResult:
        """
        Send KV cache data to an arbitrary peer node (PUT operation).
        
        Args:
            hashes: List of chunk hashes to send
            objs: List of memory objects containing the KV cache data
            transfer_spec: Dictionary containing:
                - peer_init_url: The ZMQ URL of the target peer
                - offsets: Token counts for each chunk
                - event_id: Optional event ID for request correlation
                - token_ids: Optional flat token ids for event reporting
                
        Returns:
            Transfer result with newly read, already existing, and requested counts
        """
        # Code path for `move` operation in controller.
        assert isinstance(transfer_spec, dict)
        assert "peer_init_url" in transfer_spec
        assert "offsets" in transfer_spec

        peer_init_url = transfer_spec["peer_init_url"]
        offsets = transfer_spec["offsets"]
        event_id = transfer_spec.get("event_id", "")
        token_ids = transfer_spec.get("token_ids")
        parent_hashes = transfer_spec.get("parent_hashes")
        mem_indexes = transfer_spec.get("mem_indexes")

        # Establish connection to target peer (reuses existing connection if available)
        await self._ensure_peer_connection(peer_init_url)

        if mem_indexes is None:
            mem_indexes = self.transfer_channel.get_local_mem_indices(objs)

        # Generate event_id if not provided
        if not event_id:
            event_id = f"put_{uuid.uuid4().hex[:8]}"

        # Prepare PUT message with transfer metadata
        msg = BatchedLookupAndPutMsg(
            event_id=event_id,
            sender_id=self.local_init_url,
            hashes=list(hashes),
            offsets=offsets,
            token_ids=token_ids,
            parent_hashes=parent_hashes,
            mem_indexes=list(mem_indexes),
        )

        # Update last used time and move to end (most recently used)
        self.peer_last_used_time[peer_init_url] = time.time()
        if peer_init_url in self.connected_peers:
            self.connected_peers.move_to_end(peer_init_url)

        logger.info(
                f"Sending {len(hashes)} chunks to peer {peer_init_url} "
                f"(event_id={event_id})"
            )

        try:
            # Lock-free concurrent request using event_id for correlation
            ret_msg = await self._send_request_and_wait(peer_init_url, event_id, msg)
            
            result = KvTransferPeerResult(
                num_read_chunks=ret_msg.num_read_chunks,
                num_existing_chunks=ret_msg.num_existing_chunks,
                num_requested_chunks=len(hashes),
            )
            logger.info(
                "Peer %s satisfied %d/%d chunks "
                "(%d newly read, %d already existed; event_id=%s)",
                peer_init_url,
                result.num_satisfied_chunks,
                result.num_requested_chunks,
                result.num_read_chunks,
                result.num_existing_chunks,
                event_id,
            )
            return result
        except Exception as e:
            logger.error(
                f"Failed to send data to peer {peer_init_url}: {e}. "
                f"Transfer aborted."
            )
            return KvTransferPeerResult(
                num_read_chunks=0,
                num_existing_chunks=0,
                num_requested_chunks=len(hashes),
                failed=True,
            )

    async def direct_kv_transfer(
        self,
        source_peer_init_url: str,
        target_peer_init_url: str,
        hashes: List[ChunkHash],
        offsets: Optional[List[int]] = None,
    ) -> int:
        """
        Facilitate direct KV cache transfer between two arbitrary peer nodes.
        
        This method orchestrates a transfer where data flows directly from source
        peer to target peer. The current node acts as a coordinator, instructing
        the source to send data to the target.
        
        Args:
            source_peer_init_url: The peer node that has the data
            target_peer_init_url: The peer node that should receive the data
            hashes: List of chunk hashes to transfer
            offsets: Optional list of token counts for each chunk
            
        Returns:
            Number of chunks successfully transferred
            
        Workflow:
            1. Ensure connections to both source and target peers
            2. Query source peer to verify it has the data
            3. Instruct source peer to send data directly to target peer
            4. Target peer receives and stores the data
        """
        logger.info(
            f"Orchestrating direct KV transfer: {len(hashes)} chunks from "
            f"{source_peer_init_url} to {target_peer_init_url}"
        )
        
        # Ensure connections to both peers
        await self._ensure_peer_connection(source_peer_init_url)
        await self._ensure_peer_connection(target_peer_init_url)
        
        # If offsets not provided, use default chunk_size
        if offsets is None:
            # Use default chunk_size for all keys
            offsets = [self.chunk_size] * len(hashes)
            logger.warning(
                "Offsets not provided for direct KV transfer, "
                f"using default chunk_size={self.chunk_size}"
            )
        
        # Instruct source peer to send data to target peer
        # This uses the async_batched_submit_put_task on the source side
        # Note: This requires the source peer to also be running KvTransferBackend
        try:
            # We need to send a message to source peer to initiate transfer
            # For now, we use a simplified approach: fetch from source and
            # push to target. A more optimized version would require
            # protocol extensions
            
            logger.info(
                "Direct KV transfer initiated: fetching from "
                f"{source_peer_init_url}"
            )
            
            # Step 1: Fetch data from source peer
            lookup_id = f"direct_transfer_fetch_{id(hashes)}"
            
            # Manually set up the peer mapping for batched_get
            self.lookup_id_to_peer_mapping[lookup_id] = (
                source_peer_init_url,
                "cpu",  # Assume CPU location
            )
            
            # Prepare transfer spec for get operation
            cum_chunk_lengths = [0]
            for offset in offsets:
                cum_chunk_lengths.append(cum_chunk_lengths[-1] + offset)
            
            get_transfer_spec = {
                "cum_chunk_lengths": cum_chunk_lengths,
            }
            
            fetch_keys = self._build_local_keys_from_hashes_offsets(hashes, offsets)
            mem_objs = await self.batched_get_non_blocking(
                lookup_id=lookup_id,
                keys=fetch_keys,
                transfer_spec=get_transfer_spec,
            )
            
            if not mem_objs:
                logger.error(
                    f"Failed to fetch data from source peer {source_peer_init_url}"
                )
                return 0
            
            logger.info(
                f"Direct KV transfer: pushing {len(mem_objs)} chunks to "
                f"{target_peer_init_url}"
            )
            
            # Step 2: Push data to target peer
            put_transfer_spec = {
                "peer_init_url": target_peer_init_url,
                "offsets": offsets[:len(mem_objs)],
            }
            
            num_transferred = await self.async_batched_submit_put_task(
                hashes=hashes[:len(mem_objs)],
                objs=mem_objs,
                transfer_spec=put_transfer_spec,
            )
            
            # Clean up memory objects
            for mem_obj in mem_objs:
                mem_obj.ref_count_down()
            
            logger.info(
                f"Direct KV transfer completed: {num_transferred}/{len(hashes)} chunks "
                f"transferred from {source_peer_init_url} to {target_peer_init_url}"
            )
            
            return num_transferred
            
        except Exception as e:
            logger.error(
                f"Direct KV transfer failed: {e}"
            )
            return 0
    
    def get_connected_peers(self) -> List[str]:
        return list(self.connected_peers.keys())
    
    def is_peer_connected(self, peer_init_url: str) -> bool:
        return peer_init_url in self.connected_peers
    
    def get_connection_info(self, peer_init_url: str) -> Optional[dict[str, str]]:
        if peer_init_url not in self.connected_peers:
            return None
        
        return {
            "peer_init_url": peer_init_url,
            "has_socket": peer_init_url in self.peer_to_socket_mapping,
            "has_nixl_connection": (
                peer_init_url
                in self.transfer_channel.remote_xfer_handlers_dict
            ),
        }
    
    def get_all_connections_info(self) -> dict[str, dict[str, str]]:
        return {
            peer_init_url: self.get_connection_info(peer_init_url)
            for peer_init_url in self.get_connected_peers()
        }
    
    def get_connection_pool_stats(self) -> dict:
        return {
            "current_connections": len(self.connected_peers),
            "max_connections": self.max_connections,
            "idle_timeout_seconds": self.idle_timeout_seconds,
            "cleanup_interval_seconds": self.cleanup_interval_seconds,
            **self.connection_pool_stats,
        }
    
    def get_connection_idle_times(self) -> dict[str, float]:
        current_time = time.time()
        return {
            peer_init_url: current_time - last_used_time
            for peer_init_url, last_used_time in self.peer_last_used_time.items()
        }
    
    async def cleanup_idle_connections_now(self) -> int:
        current_time = time.time()
        idle_peers = []
        
        # Find all idle connections
        for peer_init_url, last_used_time in self.peer_last_used_time.items():
            idle_duration = current_time - last_used_time
            if idle_duration > self.idle_timeout_seconds:
                idle_peers.append(peer_init_url)
        
        # Close idle connections
        for peer_init_url in idle_peers:
            self._close_peer_connection_internal(peer_init_url)
            self.connection_pool_stats["idle_timeouts"] += 1
        
        if idle_peers:
            logger.info(
                "Manual cleanup: closed %d idle connections (pool size: %d/%d)",
                len(idle_peers),
                len(self.connected_peers),
                self.max_connections,
            )
        
        return len(idle_peers)
    
    def set_connection_pool_config(
        self,
        max_connections: Optional[int] = None,
        idle_timeout_seconds: Optional[float] = None,
    ) -> None:
        if max_connections is not None:
            old_max = self.max_connections
            self.max_connections = max_connections
            logger.info(
                "Updated max_connections: %d -> %d", old_max, max_connections
            )
        
        if idle_timeout_seconds is not None:
            old_timeout = self.idle_timeout_seconds
            self.idle_timeout_seconds = idle_timeout_seconds
            logger.info(
                "Updated idle_timeout_seconds: %.1f -> %.1f",
                old_timeout,
                idle_timeout_seconds,
            )
    
    async def broadcast_to_peers(
        self,
        hashes: Sequence[ChunkHash],
        objs: List[MemoryObj],
        target_peer_urls: Optional[List[str]] = None,
        offsets: Optional[List[int]] = None,
    ) -> dict[str, int]:
        if target_peer_urls is None:
            target_peer_urls = self.get_connected_peers()
        
        if not target_peer_urls:
            logger.warning("No target peers for broadcast")
            return {}
        
        if offsets is None:
            offsets = [self.chunk_size] * len(hashes)
        
        logger.info(
            f"Broadcasting {len(hashes)} chunks to {len(target_peer_urls)} peers"
        )
        
        # Create transfer tasks for all target peers
        transfer_tasks = []
        for peer_url in target_peer_urls:
            transfer_spec = {
                "peer_init_url": peer_url,
                "offsets": offsets,
            }
            task = self.async_batched_submit_put_task(
                hashes=hashes,
                objs=objs,
                transfer_spec=transfer_spec,
            )
            transfer_tasks.append((peer_url, task))
        
        # Execute all transfers in parallel
        results = {}
        for peer_url, task in transfer_tasks:
            try:
                num_transferred = await task
                results[peer_url] = num_transferred
                logger.info(
                    f"Broadcast to {peer_url}: {num_transferred}/{len(hashes)} chunks"
                )
            except Exception as e:
                logger.error(f"Broadcast to {peer_url} failed: {e}")
                results[peer_url] = 0
        
        total_success = sum(results.values())
        logger.info(
            f"Broadcast completed: {total_success} total chunks transferred "
            f"across {len(target_peer_urls)} peers"
        )
        
        return results
    
    async def fetch_from_any_peer(
        self,
        keys: List[CacheEngineKey],
        preferred_peers: Optional[List[str]] = None,
    ) -> tuple[List[MemoryObj], str]:
        """
        Fetch KV cache data from any available peer that has it.
        
        This method tries to fetch data from preferred peers first, then falls back
        to querying the controller to find which peer has the data.
        
        Args:
            keys: List of cache keys to fetch
            preferred_peers: Optional list of peer_init_urls to try first
            
        Returns:
            Tuple of (list of memory objects, peer_init_url that provided the data)
            Returns ([], "") if data not found on any peer
        """
        logger.info(f"Attempting to fetch {len(keys)} keys from any available peer")
        
        # Try preferred peers first if specified
        if preferred_peers:
            for peer_url in preferred_peers:
                if not self.is_peer_connected(peer_url):
                    try:
                        await self._ensure_peer_connection(peer_url)
                    except Exception as e:
                        logger.warning(
                            f"Failed to connect to preferred peer "
                            f"{peer_url}: {e}"
                        )
                        continue
                
                # Try to fetch from this peer
                lookup_id = f"fetch_any_{id(keys)}_{peer_url}"
                self.lookup_id_to_peer_mapping[lookup_id] = (
                    peer_url,
                    "cpu",
                )
                
                # Prepare transfer spec
                cum_chunk_lengths = [0] + [
                    (i + 1) * self.chunk_size for i in range(len(keys))
                ]
                transfer_spec = {"cum_chunk_lengths": cum_chunk_lengths}
                
                try:
                    mem_objs = await self.batched_get_non_blocking(
                        lookup_id=lookup_id,
                        keys=keys,
                        transfer_spec=transfer_spec,
                    )
                    if mem_objs:
                        logger.info(
                            f"Successfully fetched {len(mem_objs)} chunks from "
                            f"preferred peer {peer_url}"
                        )
                        return mem_objs, peer_url
                except Exception as e:
                    logger.warning(
                        f"Failed to fetch from preferred peer "
                        f"{peer_url}: {e}"
                    )
        
        # No preferred peers succeeded, return empty
        logger.warning("Keys not found on any preferred peer")
        return [], ""
    
    def set_kv_events_sink(self, kv_events: List[CacheEvent]) -> None:
        """Inject the CacheEngine's kv_events list so that transfer events
        are appended directly to the engine's queue instead of a local one."""
        self.kv_events = kv_events

    def get_allocator_backend(self):
        return self.local_cpu_backend
    
    def _close_peer_connection_internal(self, peer_init_url: str) -> bool:
        """
        Internal method to close a peer connection without logging warnings.
        Used by cleanup tasks and LRU eviction.
        
        Args:
            peer_init_url: The initialization URL of the peer to disconnect from
            
        Returns:
            True if connection was closed, False if peer was not connected
        """
        if peer_init_url not in self.connected_peers:
            return False
        
        # Remove peer from connected set first to stop response receiver
        del self.connected_peers[peer_init_url]
        
        # Close ZMQ socket (this will also cause the response receiver to exit)
        if peer_init_url in self.peer_to_socket_mapping:
            socket = self.peer_to_socket_mapping[peer_init_url]
            try:
                socket.close()
            except Exception as e:
                logger.debug(f"Error closing socket for {peer_init_url}: {e}")
            del self.peer_to_socket_mapping[peer_init_url]
        
        # Remove last used time
        if peer_init_url in self.peer_last_used_time:
            del self.peer_last_used_time[peer_init_url]
        
        # Clean up nixl connection in transfer channel to prevent state inconsistency
        # This ensures that when we reconnect, we don't have stale nixl handlers
        if peer_init_url in self.transfer_channel.remote_xfer_handlers_dict:
            del self.transfer_channel.remote_xfer_handlers_dict[peer_init_url]
            logger.debug(
                f"Removed nixl connection handler for peer {peer_init_url}"
            )
        
        # Update statistics
        self.connection_pool_stats["total_connections_closed"] += 1
        
        return True

    def close_peer_connection(self, peer_init_url: str) -> bool:
        if peer_init_url not in self.connected_peers:
            logger.warning(f"Peer {peer_init_url} is not connected")
            return False
        
        logger.info(f"Manually closing connection to peer {peer_init_url}")
        result = self._close_peer_connection_internal(peer_init_url)
        
        if result:
            logger.info(
                "Closed connection to peer %s (pool size: %d/%d)",
                peer_init_url,
                len(self.connected_peers),
                self.max_connections,
            )
        
        return result

    def close(
        self,
    ) -> None:
        """
        Close the KvTransfer Backend and cleanup all resources.
        
        This stops the request handler and closes all peer connections.
        All cached connections (ZMQ sockets and nixl connections) are cleaned up.
        """
        self.running = False
        
        # Cancel all pending requests
        for event_id, future in self.pending_requests.items():
            if not future.done():
                future.cancel()
        self.pending_requests.clear()
        
        # Clear connected peers first (stops response receivers)
        self.connected_peers.clear()
        
        # Close all peer sockets
        for socket in self.peer_to_socket_mapping.values():
            socket.close()
        self.peer_to_socket_mapping.clear()
        
        # Close the server socket
        if hasattr(self, 'async_peer_socket'):
            self.async_peer_socket.close()
        
        # Close the transfer channel (cleans up nixl connections)
        if hasattr(self, 'transfer_channel'):
            self.transfer_channel.close()
        
        logger.info(
            "KvTransfer Backend closed successfully, all connections cleaned up"
        )

    ############################################################
    # Not-supported functions
    ############################################################

    # NOTE: synchronous contain is not supported for now.
    def contains(self, key: CacheEngineKey, pin: bool = False) -> bool:
        return False

    # NOTE: put-related functions are not supported for now.
    def exists_in_put_tasks(self, key: CacheEngineKey) -> bool:
        raise NotImplementedError

    def batched_submit_put_task(
        self,
        keys: Sequence[CacheEngineKey],
        objs: List[MemoryObj],
        transfer_spec: Any = None,
    ) -> None:
        pass

    # NOTE: Synchronous get is not supported for now.
    def get_blocking(
        self,
        key: CacheEngineKey,
    ) -> Optional[MemoryObj]:
        raise NotImplementedError

    # NOTE: pin is useless for KvTransfer Backend now.
    def pin(
        self,
        key: CacheEngineKey,
    ) -> bool:
        return False

    # NOTE: unpin is useless for KvTransfer Backend now.
    def unpin(
        self,
        key: CacheEngineKey,
    ) -> bool:
        return False

    # NOTE: remove is useless for KvTransfer Backend now.
    def remove(self, key: CacheEngineKey, force: bool = True) -> bool:
        return False
