# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kvserver_pb2 as kvserver__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kvserver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LmcacheServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferKv = channel.unary_unary(
                '/lmcache.LmcacheServer/TransferKv',
                request_serializer=kvserver__pb2.TransferKvRequest.SerializeToString,
                response_deserializer=kvserver__pb2.TransferKvResponse.FromString,
                _registered_method=True)


class LmcacheServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransferKv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LmcacheServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferKv': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferKv,
                    request_deserializer=kvserver__pb2.TransferKvRequest.FromString,
                    response_serializer=kvserver__pb2.TransferKvResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lmcache.LmcacheServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lmcache.LmcacheServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LmcacheServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransferKv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lmcache.LmcacheServer/TransferKv',
            kvserver__pb2.TransferKvRequest.SerializeToString,
            kvserver__pb2.TransferKvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
