# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lmcache_kv_transfer.proto import kvcache_v2_pb2 as kvcache__v2__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kvcache_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KvMeta2DataV2Stub:
    """V2 is additive. The kvcache.KvMeta2Data V1 service and all of its messages
    remain unchanged while clients are migrated through dual-shadow mode.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/GetCapabilities',
                request_serializer=kvcache__v2__pb2.GetCapabilitiesRequestV2.SerializeToString,
                response_deserializer=kvcache__v2__pb2.GetCapabilitiesResponseV2.FromString,
                _registered_method=True)
        self.RegisterInstance = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/RegisterInstance',
                request_serializer=kvcache__v2__pb2.RegisterInstanceV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.RegisterInstanceV2Response.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/Heartbeat',
                request_serializer=kvcache__v2__pb2.HeartbeatV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.HeartbeatV2Response.FromString,
                _registered_method=True)
        self.UnregisterInstance = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/UnregisterInstance',
                request_serializer=kvcache__v2__pb2.UnregisterInstanceV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.UnregisterInstanceV2Response.FromString,
                _registered_method=True)
        self.ReportCacheMutations = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/ReportCacheMutations',
                request_serializer=kvcache__v2__pb2.ReportCacheMutationsV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.ReportCacheMutationsV2Response.FromString,
                _registered_method=True)
        self.BeginInventorySync = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/BeginInventorySync',
                request_serializer=kvcache__v2__pb2.BeginInventorySyncV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.BeginInventorySyncV2Response.FromString,
                _registered_method=True)
        self.UploadInventoryPage = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/UploadInventoryPage',
                request_serializer=kvcache__v2__pb2.UploadInventoryPageV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.UploadInventoryPageV2Response.FromString,
                _registered_method=True)
        self.CommitInventorySync = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/CommitInventorySync',
                request_serializer=kvcache__v2__pb2.CommitInventorySyncV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.CommitInventorySyncV2Response.FromString,
                _registered_method=True)
        self.AbortInventorySync = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/AbortInventorySync',
                request_serializer=kvcache__v2__pb2.AbortInventorySyncV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.AbortInventorySyncV2Response.FromString,
                _registered_method=True)
        self.ReportRequestStart = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/ReportRequestStart',
                request_serializer=kvcache__v2__pb2.ReportRequestStartV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.ReportRequestV2Response.FromString,
                _registered_method=True)
        self.ReportRequestEnd = channel.unary_unary(
                '/kvcache.v2.KvMeta2DataV2/ReportRequestEnd',
                request_serializer=kvcache__v2__pb2.ReportRequestEndV2Request.SerializeToString,
                response_deserializer=kvcache__v2__pb2.ReportRequestV2Response.FromString,
                _registered_method=True)


class KvMeta2DataV2Servicer:
    """V2 is additive. The kvcache.KvMeta2Data V1 service and all of its messages
    remain unchanged while clients are migrated through dual-shadow mode.
    """

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCacheMutations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginInventorySync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadInventoryPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitInventorySync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortInventorySync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportRequestStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportRequestEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KvMeta2DataV2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=kvcache__v2__pb2.GetCapabilitiesRequestV2.FromString,
                    response_serializer=kvcache__v2__pb2.GetCapabilitiesResponseV2.SerializeToString,
            ),
            'RegisterInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterInstance,
                    request_deserializer=kvcache__v2__pb2.RegisterInstanceV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.RegisterInstanceV2Response.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=kvcache__v2__pb2.HeartbeatV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.HeartbeatV2Response.SerializeToString,
            ),
            'UnregisterInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterInstance,
                    request_deserializer=kvcache__v2__pb2.UnregisterInstanceV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.UnregisterInstanceV2Response.SerializeToString,
            ),
            'ReportCacheMutations': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCacheMutations,
                    request_deserializer=kvcache__v2__pb2.ReportCacheMutationsV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.ReportCacheMutationsV2Response.SerializeToString,
            ),
            'BeginInventorySync': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginInventorySync,
                    request_deserializer=kvcache__v2__pb2.BeginInventorySyncV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.BeginInventorySyncV2Response.SerializeToString,
            ),
            'UploadInventoryPage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadInventoryPage,
                    request_deserializer=kvcache__v2__pb2.UploadInventoryPageV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.UploadInventoryPageV2Response.SerializeToString,
            ),
            'CommitInventorySync': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitInventorySync,
                    request_deserializer=kvcache__v2__pb2.CommitInventorySyncV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.CommitInventorySyncV2Response.SerializeToString,
            ),
            'AbortInventorySync': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortInventorySync,
                    request_deserializer=kvcache__v2__pb2.AbortInventorySyncV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.AbortInventorySyncV2Response.SerializeToString,
            ),
            'ReportRequestStart': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportRequestStart,
                    request_deserializer=kvcache__v2__pb2.ReportRequestStartV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.ReportRequestV2Response.SerializeToString,
            ),
            'ReportRequestEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportRequestEnd,
                    request_deserializer=kvcache__v2__pb2.ReportRequestEndV2Request.FromString,
                    response_serializer=kvcache__v2__pb2.ReportRequestV2Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvcache.v2.KvMeta2DataV2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvcache.v2.KvMeta2DataV2', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KvMeta2DataV2:
    """V2 is additive. The kvcache.KvMeta2Data V1 service and all of its messages
    remain unchanged while clients are migrated through dual-shadow mode.
    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/GetCapabilities',
            kvcache__v2__pb2.GetCapabilitiesRequestV2.SerializeToString,
            kvcache__v2__pb2.GetCapabilitiesResponseV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/RegisterInstance',
            kvcache__v2__pb2.RegisterInstanceV2Request.SerializeToString,
            kvcache__v2__pb2.RegisterInstanceV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/Heartbeat',
            kvcache__v2__pb2.HeartbeatV2Request.SerializeToString,
            kvcache__v2__pb2.HeartbeatV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/UnregisterInstance',
            kvcache__v2__pb2.UnregisterInstanceV2Request.SerializeToString,
            kvcache__v2__pb2.UnregisterInstanceV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCacheMutations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/ReportCacheMutations',
            kvcache__v2__pb2.ReportCacheMutationsV2Request.SerializeToString,
            kvcache__v2__pb2.ReportCacheMutationsV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginInventorySync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/BeginInventorySync',
            kvcache__v2__pb2.BeginInventorySyncV2Request.SerializeToString,
            kvcache__v2__pb2.BeginInventorySyncV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadInventoryPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/UploadInventoryPage',
            kvcache__v2__pb2.UploadInventoryPageV2Request.SerializeToString,
            kvcache__v2__pb2.UploadInventoryPageV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitInventorySync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/CommitInventorySync',
            kvcache__v2__pb2.CommitInventorySyncV2Request.SerializeToString,
            kvcache__v2__pb2.CommitInventorySyncV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortInventorySync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/AbortInventorySync',
            kvcache__v2__pb2.AbortInventorySyncV2Request.SerializeToString,
            kvcache__v2__pb2.AbortInventorySyncV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportRequestStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/ReportRequestStart',
            kvcache__v2__pb2.ReportRequestStartV2Request.SerializeToString,
            kvcache__v2__pb2.ReportRequestV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportRequestEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvcache.v2.KvMeta2DataV2/ReportRequestEnd',
            kvcache__v2__pb2.ReportRequestEndV2Request.SerializeToString,
            kvcache__v2__pb2.ReportRequestV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
