# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvserver_v2.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'kvserver_v2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lmcache_kv_transfer.proto import kvcache_v2_pb2 as kvcache__v2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11kvserver_v2.proto\x12\nlmcache.v2\x1a\x10kvcache_v2.proto\"\xbf\x02\n\x13TransferKvV2Request\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x1e\n\x16\x63ompatibility_group_id\x18\x02 \x01(\x0c\x12.\n\x06source\x18\x03 \x01(\x0b\x32\x1e.kvcache.v2.InstanceIdentityV2\x12.\n\x06target\x18\x04 \x01(\x0b\x32\x1e.kvcache.v2.InstanceIdentityV2\x12\x39\n\x10target_endpoints\x18\x05 \x01(\x0b\x32\x1f.kvcache.v2.InstanceEndpointsV2\x12-\n\x06\x62locks\x18\x06 \x03(\x0b\x32\x1d.kvcache.v2.BlockDescriptorV2\x12\x0f\n\x07\x64o_copy\x18\x07 \x01(\x08\x12\x18\n\x10\x64\x65\x61\x64line_unix_ms\x18\x08 \x01(\x04\"\xb2\x01\n\x15\x42lockTransferResultV2\x12\x10\n\x08seq_hash\x18\x01 \x01(\x0c\x12\x31\n\x06status\x18\x02 \x01(\x0e\x32!.lmcache.v2.BlockTransferStatusV2\x12\x1e\n\x16target_replica_version\x18\x03 \x01(\x04\x12\x19\n\x11\x62ytes_transferred\x18\x04 \x01(\x04\x12\x19\n\x11\x65rror_detail_code\x18\x05 \x01(\t\"_\n\x14TransferKvV2Response\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x32\n\x07results\x18\x02 \x03(\x0b\x32!.lmcache.v2.BlockTransferResultV2*\xd1\x03\n\x15\x42lockTransferStatusV2\x12(\n$BLOCK_TRANSFER_STATUS_V2_UNSPECIFIED\x10\x00\x12#\n\x1f\x42LOCK_TRANSFER_STATUS_V2_COPIED\x10\x01\x12,\n(BLOCK_TRANSFER_STATUS_V2_ALREADY_PRESENT\x10\x02\x12+\n\'BLOCK_TRANSFER_STATUS_V2_SOURCE_MISSING\x10\x03\x12/\n+BLOCK_TRANSFER_STATUS_V2_TARGET_NO_CAPACITY\x10\x04\x12(\n$BLOCK_TRANSFER_STATUS_V2_READ_FAILED\x10\x05\x12*\n&BLOCK_TRANSFER_STATUS_V2_NOT_ATTEMPTED\x10\x06\x12)\n%BLOCK_TRANSFER_STATUS_V2_INCOMPATIBLE\x10\x07\x12/\n+BLOCK_TRANSFER_STATUS_V2_STALE_TARGET_EPOCH\x10\x08\x12+\n\'BLOCK_TRANSFER_STATUS_V2_PROTOCOL_ERROR\x10\t2d\n\x0fLmcacheServerV2\x12Q\n\x0cTransferKvV2\x12\x1f.lmcache.v2.TransferKvV2Request\x1a .lmcache.v2.TransferKvV2Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvserver_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCKTRANSFERSTATUSV2']._serialized_start=652
  _globals['_BLOCKTRANSFERSTATUSV2']._serialized_end=1117
  _globals['_TRANSFERKVV2REQUEST']._serialized_start=52
  _globals['_TRANSFERKVV2REQUEST']._serialized_end=371
  _globals['_BLOCKTRANSFERRESULTV2']._serialized_start=374
  _globals['_BLOCKTRANSFERRESULTV2']._serialized_end=552
  _globals['_TRANSFERKVV2RESPONSE']._serialized_start=554
  _globals['_TRANSFERKVV2RESPONSE']._serialized_end=649
  _globals['_LMCACHESERVERV2']._serialized_start=1119
  _globals['_LMCACHESERVERV2']._serialized_end=1219
# @@protoc_insertion_point(module_scope)
